### ISSUE TITLE
Add Navbar with home, about, map and github tabs

### ISSUE THREAD

**Issue by Fridish** [Fridish/Charging-Stations#11]
Add a navbar to navigate between home, the map and an about-page (the about-page does not exist yet), as well as an icon button that leads the user to this directory.

**Comment by Maanaesh** [comment]
i can take up this issue if it's still available

**Comment by Fridish** [comment]
Certainly! I have assigned the issue to you. Thank you for contributing!

**Comment by Maanaesh** [comment]
> Certainly! I have assigned the issue to you. Thank you for contributing!

can you close this issue now that it's over
